import { Poppins, Philosopher, La_Belle_Aurore } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar/Navbar";
import Footer from "./Components/Footer/Footer";
import Providers from "@/store/providers";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const philosopher = Philosopher({
  variable: "--font-philosopher",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const laBelleAurore = La_Belle_Aurore({
  variable: "--font-la-belle-aurore",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${poppins.className} ${philosopher.variable} ${laBelleAurore.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* header section  */}
        <header>
          <Navbar />
        </header>

        {/* main section  */}
        <main className="flex-grow pt-16 lg:pt-0">
          <Providers>{children}</Providers>
        </main>

        {/* footer section  */}
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}